# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6241432842ad5141ab8ee770fbdb240ea4d3b54ba306c975beaa0314fca79db912f18b736911eccdcd7be09371d8eda66966a8d93d0c954527828de13dc7206c

test:
  secret_key_base: 7b76a4766f9ec07a808d2e60a9fbea3db3f95699ac032475dc457e7025fe1aad30b3319e8c8587948efdfebac457e174d87a445f447050f6bb4f907041eaece1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
